### ISSUE TITLE
Source code 

### ISSUE THREAD

**Issue by jf3218** [dledmonds/quake3-nemesis-1.16n#1]
Hi, 
 Yes, can you  release the source code  client and server please  :)

Thanks you!

**Comment by dledmonds** [comment]
Give me a few weeks to sort it out and I'll release it.

**Comment by jf3218** [comment]
thank you would greatly appreciate it.

**Comment by if4te** [comment]
Hello Darren, I too am interested in having the nemesis code.. can you please release? 

Thanks, Lil

**Comment by dledmonds** [comment]
Looks like few weeks turned into few months! Good news is I have the code from backup, so will try and upload tomorrow after some small tweaks.

**Comment by MHT417** [comment]
thanks


________________________________

**Comment by dledmonds** [comment]
Client side code released.

**Comment by jf3218** [comment]
Thank you Darren :)
